[package]
name = "funding-service-design-notification"
version = "0.1.1"
description = "The funding service design notification service for the DLUHC."
authors = ["DLUHC"]
license = "MIT License"

[tool.black]
line-length = 79
experimental-string-processing = 1
