openapi: "3.0.0"
info:
  description: Notification service API for DLUHC Funding Service Design
  version: "0.1.0"
  title: Funding Service Design - Notification service

paths:
  /send:
    post:
      tags:
        -  Notification
      summary: Service forwards the requested contents to the user i.e. "magic link"
      operationId: app.notification.model.send_email
      requestBody:
        description: Magic link metadata
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
            example:
              type: 'MAGIC_LINK'
              to: 'example@email.com'
              content: {"magic_link_url": "https://www.example.com/",}
      responses:
        200:
          description: "Contents have successfully been delivered"
        400:
          description: "Bad request - incorrect contents"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralError'

components:
  schemas:
    GeneralError:
      type: object
      properties:
        title:
          type: string
          example: "Bad request"
        type:
          type: object
          example: "about:blank"
        status:
          type: integer
          format: int32
          example: 400
        detail:
          type: string
          example: "'type' is a required key"
    Notification:
      description:
        "Service requires three keys
        (type-string, to-email, content-dict)"
      required:
        - type
        - to
        - content
      properties:
        type:
          type: string
          example: "MAGIC_LINK"
        to:
          type: string
          example: "example@email.com"
        content:
          type: object
          properties:
            magic_link_url:
              type: string
            fund_name:
              type: string
          example: {"magic_link_url": "https://www.example.com/",
                    "fund_name": "Funding service"}
