openapi: "3.0.0"
info:
  description: Notification service API for DLUHC Funding Service Design
  version: "0.1.0"
  title: Funding Service Design - Notification service

paths:
  /send:
    post:
      tags:
        -  Notification
      summary: Service forwards the requested contents to the user i.e. "magic link"
      operationId: app.notification.model.send_email
      requestBody:
        description: Magic link metadata
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: 'components.yml#/components/schemas/Magic_Link'
                - $ref: 'components.yml#/components/schemas/Submitted_Application'
                - $ref: 'components.yml#/components/schemas/Incomplete_Application'
                - $ref: 'components.yml#/components/schemas/Application_Reminder'

            example:
              type: 'MAGIC_LINK'
              to: 'example@email.com'
              content: {
                "magic_link_url": "https://www.example.com/",
                "fund_name": "Funding service",
                "request_new_link_url": "https://www.example.com/new_link",
                "contact_help_email": "COF@communities.gov.uk"
              }
      responses:
        200:
          description: "Contents have successfully been delivered"
        400:
          description: "Bad request - incorrect contents"
          content:
            application/json:
              schema:
                $ref: 'components.yml#/components/schemas/GeneralError'
