name: Deploy to AWS
on:
  workflow_dispatch:
    inputs:
      environment:
        description:  Which AWS Account to use
        type: choice
        required: true
        options:
        - dev
        - test
        - uat
        - production
      run_performance_tests:
        required: false
        default: false
        type: boolean
        description: Run performance tests
      run_e2e_tests:
        required: false
        default: true
        type: boolean
        description: Run e2e tests
  push:
    # Ignore README markdown
    # Only automatically deploy when something in the app or tests folder has changed
    paths:
      - '!**/README.md'
      - 'app/**'
      - 'tests/**'

jobs:
  paketo_build:
    permissions:
      packages: write
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/package.yml@main
    with:
      version_to_build: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
      owner: ${{ github.repository_owner }}
      application: funding-service-design-notification

  pre_deploy_tests:
    secrets:
      E2E_PAT: ${{secrets.E2E_PAT}}
      GOV_NOTIFY_API_KEY: ${{secrets.GOV_NOTIFY_API_KEY}}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/pre-deploy.yml@main
    with:
      postgres_unit_testing: false

  copilot_deploy_dev:
    if: inputs.environment == 'dev' || inputs.environment == ''
    needs: [pre_deploy_tests, paketo_build]
    concurrency: deploy-dev
    uses: ./.github/workflows/environment.yml
    with:
      workspace: 'dev'

  copilot_deploy_test:
    if: inputs.environment == 'test' || inputs.environment == ''
    needs: [pre_deploy_tests, paketo_build]
    concurrency: deploy-test
    uses: ./.github/workflows/environment.yml
    with:
      workspace: 'test'

  post_deploy_tests:
      needs: copilot_deploy_test
      secrets:
        E2E_PAT: ${{secrets.E2E_PAT}}
      uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@main
      with:
        run_performance_tests: ${{ inputs.run_performance_tests }}
        run_e2e_tests: ${{ inputs.run_e2e_tests }}
        app_name: notification
