name: Deploy to AWS
on:
  workflow_dispatch:
    inputs:
      environment:
        description:  Which AWS Account to use
        type: choice
        required: true
        options:
        - dev
        - test
        - uat
        - prod
      run_performance_tests:
        required: false
        default: false
        type: boolean
        description: Run performance tests
      run_e2e_tests:
        required: false
        default: true
        type: boolean
        description: Run e2e tests
  push:
    # Ignore README markdown
    # Only automatically deploy when something in the app or tests folder has changed
    paths:
      - '!**/README.md'
      - 'app/**'
      - 'config/**'
      - 'tests/**'
      - 'requirements-dev.in'
      - 'requirements-dev.txt'
      - 'requirements.in'
      - 'requirements.txt'
      - '.github/workflows/copilot_deploy.yml'

jobs:
  tag_version:
    runs-on: ubuntu-latest
    outputs:
      version_to_tag: ${{ steps.notification_tagging.outputs.tag_value }}
    steps:
      - id: notification_tagging
        run: |
          echo "tag_value=$(echo '${{ github.ref }}' | sed -e 's,.*/\(.*\),\1,')" >> $GITHUB_OUTPUT

  pre_deploy_tests:
    secrets:
      GOV_NOTIFY_API_KEY: ${{ secrets.GOV_NOTIFY_API_KEY }}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/pre-deploy.yml@main
    with:
      postgres_unit_testing: false

  paketo_build:
    needs: [ tag_version ]
    concurrency: build-notification-pack
    permissions:
      packages: write
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/package.yml@main
    with:
      version_to_build: ${{ needs.tag_version.outputs.version_to_tag }}
      owner: ${{ github.repository_owner }}
      application: funding-service-design-notification

  copilot_environments_workflow_setup:
    runs-on: ubuntu-latest
    outputs:
      env_list: ${{ steps.copilot_env_list.outputs.env_list }}
      ind_list: ${{ steps.copilot_env_list.outputs.ind_list }}
    steps:
      - id: copilot_env_matrix
        run: |
          echo "ind_list=[]" >> $GITHUB_OUTPUT
          echo "env_list=[]" >> $GITHUB_OUTPUT
          if [ "${{ inputs.environment }}" != "" ]; then
            echo "ind_list=[\"${{ inputs.environment }}\"]" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == 'refs/heads/main' ]; then
            echo "env_list=[\"dev\", \"test\", \"uat\", \"prod\"]" >> $GITHUB_OUTPUT
          else
            echo "env_list=[\"dev\", \"test\"]" >> $GITHUB_OUTPUT
          fi

  ind_deploy:
    if: ${{ needs.copilot_environments_workflow_setup.outputs.ind_list != '[]' }}
    concurrency:
      group: 'fsd-preaward-copilot-dev'
      cancel-in-progress: false
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@BAU_standardise_deploy
    with:
      env: 'dev'
      app_name: 'notification'
      version: ${{ github.ref_name == 'main' && 'latest' || needs.tag_version.outputs.version_to_tag }}

  dev_deploy:
    if: ${{ contains(needs.copilot_environments_workflow_setup.outputs.env_list, 'dev')
    concurrency:
      group: 'fsd-preaward-copilot-dev'
      cancel-in-progress: false
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@BAU_standardise_deploy
    with:
      env: 'dev'
      app_name: 'notification'
      version: ${{ github.ref_name == 'main' && 'latest' || needs.tag_version.outputs.version_to_tag }}

  post_dev_deploy_tests:
    needs: dev_deploy
    concurrency:
      group: 'fsd-preaward-test-dev'
      cancel-in-progress: false
    secrets:
      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@main
    with:
      run_performance_tests: ${{ inputs.run_performance_tests || true }}
      run_e2e_tests: ${{ inputs.run_e2e_tests || false }}
      environment: dev

  test_deploy:
    if: ${{ contains(needs.copilot_environments_workflow_setup.outputs.env_list, 'test')
    concurrency:
      group: 'fsd-preaward-copilot-dev'
      cancel-in-progress: false
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@BAU_standardise_deploy
    with:
      env: 'test'
      app_name: 'notification'
      version: ${{ github.ref_name == 'main' && 'latest' || needs.tag_version.outputs.version_to_tag }}
    needs: [ tag_version, copilot_environments_workflow_setup ]

  post_test_deploy_tests:
    needs: test_deploy
    concurrency:
      group: 'fsd-preaward-test-test'
      cancel-in-progress: false
    secrets:
      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@main
    with:
      run_performance_tests: ${{ inputs.run_performance_tests || true }}
      run_e2e_tests: ${{ inputs.run_e2e_tests || true }}
      environment: test

  uat_deploy:
    if: ${{ contains(needs.copilot_environments_workflow_setup.outputs.env_list, 'uat')
    concurrency:
      group: 'fsd-preaward-copilot-dev'
      cancel-in-progress: false
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@BAU_standardise_deploy
    with:
      env: 'uat'
      app_name: 'notification'
      version: ${{ github.ref_name == 'main' && 'latest' || needs.tag_version.outputs.version_to_tag }}
    needs: [ tag_version, post_test_deploy_tests, copilot_environments_workflow_setup ]

  post_uat_deploy_tests:
    needs: uat_deploy
    concurrency:
      group: 'fsd-preaward-test-uat'
      cancel-in-progress: false
    secrets:
      FSD_GH_APP_ID: ${{ secrets.FSD_GH_APP_ID }}
      FSD_GH_APP_KEY: ${{ secrets.FSD_GH_APP_KEY }}
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/post-deploy.yml@main
    with:
      run_performance_tests: ${{ inputs.run_performance_tests || false }}
      run_e2e_tests: ${{ inputs.run_e2e_tests || true }}
      environment: uat

  prod_deploy:
    if: ${{ contains(needs.copilot_environments_workflow_setup.outputs.env_list, 'prod')
    concurrency:
      group: 'fsd-preaward-copilot-dev'
      cancel-in-progress: false
    uses: communitiesuk/funding-service-design-workflows/.github/workflows/standard-deploy.yml@BAU_standardise_deploy
    with:
      env: 'prod'
      app_name: 'notification'
      version: ${{ github.ref_name == 'main' && 'latest' || needs.tag_version.outputs.version_to_tag }}
    needs: [ tag_version, post_uat_deploy_tests, copilot_environments_workflow_setup ]
