name: Deploy to Gov PaaS

on:
  workflow_dispatch:
  push:
    # branches:
    # - master
    # - FS-389
    # - FS-390

    paths-ignore:
      - '**/README.md'

jobs:
  testing:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.x
      - name: install dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r requirements-dev.txt
      - name: run unit tests
        run: python -m pip install pytest && python -m pytest .
        env:
          GOV_NOTIFY_API_KEY: ${{secrets.GOV_NOTIFY_API_KEY}}

  deploy_dev:
    if: ${{ github.actor != 'dependabot[bot]' }}
    concurrency: deploy_dev_${{github.repository}}
    needs: testing
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.x
      - name: create python env
        run: python -m venv .venv
      - name: install dependencies
        run: source .venv/bin/activate && python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Deploy to Gov PaaS
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api:      ${{secrets.CF_API}}
          cf_org:      ${{secrets.CF_ORG}}
          cf_space:    ${{secrets.CF_SPACE }}
          cf_username: ${{secrets.CF_USERNAME}}
          cf_password: ${{secrets.CF_PASSWORD}}
          command: push funding-service-design-notification-dev  --var GOV_NOTIFY_API_KEY=${{secrets.GOV_NOTIFY_API_KEY}} --var GITHUB_SHA="${{ github.sha }}"


  run-shared-tests_dev:
    needs: deploy_dev
    concurrency: run-shared-tests_dev
    if: ${{ github.actor != 'dependabot[bot]'}}
    uses: communitiesuk/funding-design-service-workflows/.github/workflows/run-shared-tests.yml@main
    with:
      perf_test_target_url_application_store: https://funding-service-design-application-store-dev.london.cloudapps.digital
      perf_test_target_url_fund_store: https://funding-service-design-fund-store-dev.london.cloudapps.digital
      perf_test_target_url_assessment_store: https://funding-service-design-assessment-store-dev.london.cloudapps.digital
      e2e_tests_target_url_frontend: https://fsd:fsd@frontend.dev.gids.dev
      e2e_tests_target_url_authenticator: https://fsd:fsd@authenticator2.dev.gids.dev
      e2e_tests_target_url_form_runner: https://fsd:fsd@forms.dev.gids.dev
      e2e_tests_target_url_assessment: https://fsd:fsd@assessment.dev.gids.dev
      run_performance_tests: true
      run_e2e_tests: false
    secrets:
       E2E_PAT: ${{secrets.E2E_PAT}}

  security:
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.x
      - name: install dependencies
        run: python -m pip install --upgrade pip && python -m pip install -r requirements-dev.txt
      - name: Bandit
        run: bandit -r ./app
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'https://funding-service-design-notification-dev.london.cloudapps.digital/'
          allow_issue_writing: False

  deploy_test:
    if: ${{ github.ref == 'refs/heads/main' }}
    concurrency: deploy_test_${{github.repository}}
    # TODO: restore this once security check can pass, see https://communities-govuk.slack.com/archives/C02PHBER287/p1664794101631599
    # needs: security
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.x
      - name: create python env
        run: python -m venv .venv
      - name: install dependencies
        run: source .venv/bin/activate && python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Deploy to Gov PaaS
        uses: citizen-of-planet-earth/cf-cli-action@v2
        with:
          cf_api:      ${{secrets.CF_API}}
          cf_org:      ${{secrets.CF_ORG}}
          cf_space:    ${{secrets.CF_SPACE }}
          cf_username: ${{secrets.CF_USERNAME}}
          cf_password: ${{secrets.CF_PASSWORD}}
          command: push funding-service-design-notification-test  --var GOV_NOTIFY_API_KEY=${{secrets.GOV_NOTIFY_API_KEY}} --var GITHUB_SHA="${{ github.sha }}"


  run-shared-tests_test:
    needs: deploy_test
    concurrency: run-shared-tests_test
    if: ${{ github.actor != 'dependabot[bot]'}}
    uses: communitiesuk/funding-design-service-workflows/.github/workflows/run-shared-tests.yml@main
    with:
      perf_test_target_url_application_store: https://funding-service-design-application-store-test.london.cloudapps.digital
      perf_test_target_url_fund_store: https://funding-service-design-fund-store-test.london.cloudapps.digital
      perf_test_target_url_assessment_store: https://funding-service-design-assessment-store-test.london.cloudapps.digital
      e2e_tests_target_url_frontend: https://fsd:fsd@frontend.test.gids.dev
      e2e_tests_target_url_authenticator: https://fsd:fsd@authenticator2.test.gids.dev
      e2e_tests_target_url_form_runner: https://fsd:fsd@forms.test.gids.dev
      e2e_tests_target_url_assessment: https://fsd:fsd@assessment.test.gids.dev
      run_performance_tests: true
      run_e2e_tests: true
    secrets:
       E2E_PAT: ${{secrets.E2E_PAT}}
